BLOCO('revelacao/logo-pilulas', function ({ tl, K, root, $, cena, cue, texto }) {
  const logo = $('.logo'), glow = $('.glow4'), tag = $('.tag')
  tl.fromTo(glow, { opacity: 0, scale: 0.6 }, { opacity: 1, scale: 1, duration: 1.0, ease: 'power2.out' }, cue('entra') - 0.2)
  tl.fromTo(logo, { clipPath: 'inset(0 100% 0 0)', scale: 0.9 }, { clipPath: 'inset(0 0% 0 0)', scale: 1, duration: 0.85, ease: 'power3.out' }, cue('entra') - 0.18)
  tl.to(logo, { scale: 1.05, duration: 0.18, ease: 'power2.out', yoyo: true, repeat: 1 }, cue('marca'))
  K.burst($('.burst4'), cue('marca'), 1.2)
  tl.to(glow, { scale: 1.12, duration: 0.9, ease: 'sine.inOut', yoyo: true, repeat: 1 }, cue('marca') + 0.3)
  tl.to(logo, { y: -18, duration: Math.max(0.4, cue('assinatura') - cue('marca') - 0.3), ease: 'sine.inOut' }, cue('marca') + 0.35)
  $('.tag .tx').textContent = texto('assinatura')
  tl.fromTo(tag, { opacity: 0, y: 30 }, { opacity: 1, y: 0, ...M.FAST }, cue('assinatura'))
  K.pop($('.tag .tile-ic'), cue('assinatura') + 0.05, 0.3)
  // o título: logo e assinatura sobem e encolhem; headline e pílulas entram uma a uma
  tl.to(logo, { y: -190, scale: 0.62, duration: 0.7, ease: M.GENTLE.ease }, cue('titulo'))
  tl.to(glow, { y: -230, scale: 0.7, duration: 0.7, ease: M.GENTLE.ease }, cue('titulo'))
  tl.to(tag, { y: -350, scale: 0.8, duration: 0.7, ease: M.GENTLE.ease }, cue('titulo'))
  K.flash($('.h4'), texto('titulo'), cue('titulo') + 0.15)
  ;['p1', 'p2', 'p3'].forEach((p, i) => {
    const el = $('.' + p)
    el.querySelector('.tx').textContent = texto(p)
    const at = cue(p)
    tl.fromTo(el, { opacity: 0, x: i % 2 ? 80 : -80, scale: 0.85 }, { opacity: 1, x: 0, scale: 1, ...M.SOFT }, at)
    tl.fromTo(el.querySelector('.tile-ic'), { rotation: -90, scale: 0.3 }, { rotation: 0, scale: 1, ...M.SOFT }, at + 0.06)
  })
  tl.to($('.p3'), { scale: 1.06, duration: 0.22, ease: 'sine.inOut', yoyo: true, repeat: 1 }, cue('p3') + 0.55)
  tl.fromTo(root, { scale: 1 }, { scale: 1.03, duration: cena.dur, ease: 'sine.inOut' }, cena.start)
  K.out(root, cena.end - 0.27, 0.28, -40)
})
