BLOCO('produto/painel-inicio', function ({ tl, K, $, $$, cena, cue, texto, fala, box, cursor }) {
  const f = fala(0)
  const app = $('.app')
  // medir antes de qualquer transform; a "câmera" (scale do painel em torno de O) é aplicada à mão nos alvos do cursor
  const a = box(app, 0.5, 0.4), O = { x: a.x, y: a.y }
  const cam = (p, s, dx, dy) => ({ x: O.x + (p.x - O.x) * s + dx, y: O.y + (p.y - O.y) * s + dy })
  const pIniciar = cam(box($('.next .btn.pri'), 0.55, 0.6), 1.05, 0, 30)
  const pList = cam(box($('.list .sess:nth-of-type(2)'), 0.8, 0.6), 1.05, 0, -15)

  $('.hello').innerHTML = `${texto('saudacao')} <span class="acc">${texto('nome')}</span>`
  K.type($('.h5a'), texto('h1'), f, cue('entra') + 0.05, 34, true)
  K.out($('.h5a'), cue('destaque') - 0.2, 0.2, -30)
  K.type($('.h5b'), texto('h2'), f, cue('destaque'), 34, true)
  K.out($('.h5b'), cue('lista') - 0.2, 0.2, -30)
  K.type($('.h5c'), texto('h3'), f, cue('lista'), 34, true)
  tl.fromTo(app, { opacity: 0 }, { opacity: 1, duration: 0.25, ease: 'power1.out' }, cue('entra') - 0.18)
  tl.fromTo(app, { y: 140, scale: 0.92 }, { y: 0, scale: 1, ...M.GENTLE, duration: 0.9 }, cue('entra') - 0.18)
  tl.fromTo($('.next'), { opacity: 0, y: 40 }, { opacity: 1, y: 0, ...M.FAST }, cue('entra') + 0.15)
  tl.fromTo([$('.list'), $('.short')], { opacity: 0, y: 40 }, { opacity: 1, y: 0, ...M.FAST, stagger: 0.08 }, cue('entra') + 0.25)
  $$('.list .sess').forEach((el, i) => tl.fromTo(el, { opacity: 0, x: -24 }, { opacity: 1, x: 0, ...M.FAST }, cue('entra') + 0.4 + i * 0.07))
  $$('.tile').forEach((el, i) => tl.fromTo(el, { opacity: 0, scale: 0.85 }, { opacity: 1, scale: 1, ...M.SOFT }, cue('entra') + 0.45 + i * 0.07))
  tl.to(app, { scale: 1.05, y: 30, duration: 1.1, ease: M.GENTLE.ease }, cue('destaque') - 0.2)
  tl.fromTo($('.ring5'), { opacity: 0, scale: 1.04 }, { opacity: 1, scale: 1, ...M.FAST }, cue('destaque'))
  const C = cursor()
  tl.set(C.el, { x: pIniciar.x + 300, y: pIniciar.y + 260 }, cena.start)
  tl.to(C.el, { opacity: 1, duration: 0.2 }, cue('destaque') - 0.1)
  C.move(pIniciar, cue('destaque') - 0.1, 0.65)
  tl.to($('.ring5'), { opacity: 0, duration: 0.25 }, cue('lista') - 0.2)
  tl.to(app, { scale: 1.05, y: -15, duration: 1.1, ease: M.GENTLE.ease }, cue('lista') - 0.2)
  C.move(pList, cue('lista') - 0.15, 0.6)
  tl.to($('.list .sess:nth-of-type(2)'), { backgroundColor: 'var(--ui-glow)', borderColor: 'var(--accent-soft)', duration: 0.25 }, cue('lista') + 0.4)
  C.click(pList, cue('lista') + 0.45)
  tl.fromTo($('.done'), { opacity: 0, y: 40, scale: 0.92 }, { opacity: 1, y: 0, scale: 1, ...M.SOFT }, cue('feito'))
  K.pop($('.done .icon'), cue('feito') + 0.12, 0.2)
  tl.to(C.el, { opacity: 0, duration: 0.2 }, cue('sai') - 0.15)
  tl.to(app, { opacity: 0, scale: 0.9, filter: 'blur(10px)', duration: 0.3, ease: 'power2.in' }, cue('sai'))
  K.out($('.h5c'), cue('sai'), 0.28)
})
