BLOCO('virada/riscar-e-cuidar', function ({ tl, K, root, $, $$, cena, cue, texto, fala }) {
  const f = fala(0)
  const tiles = $$('.admin .tile-ic')
  tiles.forEach((el, i) => K.pop(el, cue('entra') + i * 0.08, 0.3))
  $('.l1t').textContent = texto('antes')
  tl.fromTo($('.l1'), { opacity: 0, y: 30 }, { opacity: 1, y: 0, ...M.FAST }, cue('entra') + 0.1)
  tl.to($('.strike'), { scaleX: 1, duration: 0.45, ease: 'power2.inOut' }, cue('risca'))
  tiles.forEach((el, i) => tl.to(el, { y: -50, scale: 0.5, rotation: (i - 1) * 25, opacity: 0, duration: 0.4, ease: 'power2.in' }, cue('risca') + 0.15 + i * 0.05))
  tl.to($('.l1'), { opacity: 0.6, y: -230, scale: 0.8, duration: 0.6, ease: M.GENTLE.ease }, cue('troca') - 0.1)
  K.type($('.l2'), texto('depois'), f, cue('troca'))
  K.pop($('.heart6'), cue('coracao'), 0.2)
  K.burst($('.burst6'), cue('coracao') + 0.05, 2.0)
  tl.to($('.heart6'), { scale: 1.12, duration: 0.22, ease: 'sine.inOut', yoyo: true, repeat: 1 }, cue('coracao') + 0.7)
  tl.fromTo(root, { scale: 1 }, { scale: 1.04, duration: cena.dur, ease: 'sine.inOut' }, cena.start)
  K.out(root, cena.end - 0.26, 0.28, -40)
})
